# 宋女性

## 刘后

宋真宗宫内。

### 《宋人轶事汇编·卷一》

1. 章献明肃太后，成都华阳人。少随父下峡至玉泉寺，有长老者善相人，谓其父曰：‘君，贵人也。’及见后，则大惊曰：‘君之贵以此女也。’又曰：‘远方不足留，盍游京师乎？’父以贫为辞，长老者赠以中金百两。后之家至京师，真宗判南衙，因张耆纳后宫中。帝即位，为才人，进宸妃，至正位宫闱，声势动天下。仁宗即位，以太皇太后垂帘听政。玉泉长老者，已居长芦矣。后屡召不至，遣使就问所须，则曰：‘道人无所须也。玉泉寺无僧堂，长芦寺无山门，后其念之。’后以本阁服用物下两寺为钱，以建长芦寺临江门，起水中。……今《玉泉寺僧堂梁记》曰后所建云。《邵氏闻见录》卷一。《群书类编故事》卷四。
2. 宋章献明肃皇后本成都之华阳人，家以播鼗为业。随父龚美游汴，过荆门，止玉泉寺，慕容禅师夜梦金刚报云：‘明日女中天子过此。’因厚遇之，赠以金。时真宗尚为寿王，居潜邸，知客张耆引后见王，王悦，遂纳之。《涌幢小品》卷二十八。
3. 章献刘后本蜀人，善播鼗。蜀人宫美之入京。美以锻银为业，时真宗为皇太子，尹开封，美因锻得见，太子语之曰：‘蜀妇人多材慧，汝为我求一蜀姬。’美因纳后于太子，见之，大悦，宠幸专房。太子乳母恶之。太宗尝问乳母：‘太子近日容貌癯瘠，左右有何人？’乳母以后对，上命去之。太子不得已，置于殿侍张耆之家。耆避嫌，为之不敢下直。未几，太宗宴驾，太子即帝位，复召入宫。《涑水记闻》卷五。
4. 宫美以锻银为业，纳邻倡妇刘氏为妻，善播鼗。既而家贫，复售之。张耆时为襄王宫指使，言于王，得召入宫，大有宠。王乳母秦国夫人性严整，恶之，固令王斥去。王不得已，置于张耆家，以银五挺与之，使筑馆居于外。徐使人请于秦国夫人，乃许复召入宫。美由是得为开封府通引官，给事王宫。及王即帝位，刘氏为美人，以其无宗族，更以美为弟，改姓刘云。乐道父与张耆具为襄王宫指使，故得详耳。《涑水记闻》卷六。
5. 钱思公嫁女，令银匠龚美打造装奁器皿。既而美拜官，思公即取美为妹婿，向所打造器皿归美家。《东轩笔录》卷十五。《野客丛书》卷十一。《宋稗类钞》卷一。
6. 章献明肃初自蜀中泛江而下，舟过真州之长芦，有闽僧法灯者，筑茅庵岸旁。灯一见，听其歌声，许以必贵，倒囊津置入京，继遂遭际。及位长乐，灯尚在，后捐奁中百万缗，命淮南、两浙、江南三路转运使创建大刹，工巧雄丽，甲于南北。俾灯住持，赐予不绝。李邯郸为之碑，至今存焉。《挥麈余话》卷一。
7. 见吕夷简13。
8. 章献太后智聪过人。其垂帘之时，一日，泣语大臣曰：‘国家多难如此，向非宰执同心协力，何以至此？今山陵了毕，皇亲外戚各已迁转推恩，惟宰执臣寮亲戚无有恩泽。卿等可尽具子孙内外亲族姓名来，当例外一一尽数推恩。’宰执不悟，于是尽具三族亲戚姓名以奏闻。明肃得之，遂各画成图，粘之寝殿壁间。每有进拟，必先观图上，非两府亲戚姓名中所有者方除之。《默记》卷上。
9. 明肃太后临朝，袭真宗故事，留心庶狱，日遣中使至军巡院、御史台，体问鞠囚情节。又好问外事，每中使出入，必委曲询究，故百官细微，无不知者。有孙良孺为军巡判官，喜诈伪，能为朴野之状。一日，市布数十端，杂染五色，陈于庭下。中使怪而问之，良孺曰：‘家有一女，出适在近，与之作少衣物也。’中使大骇，回为太后言之，太后叹其清苦，即命厚赐金帛。京师人多赁马出入，驭者先许其直，必问曰：‘一去耶？却来耶？’苟乘以往来，则其价倍于一去也。良孺以贫，不养马，每出，必赁之。一日将押大辟囚弃市，而赁马以往，其驭者问曰：‘官人将何之？’良孺曰：‘至法场头。’驭者曰：‘一去耶？却来耶？’闻者骇笑。《东轩笔录》卷九。《宋朝事实类苑》卷六十五。
10. 仁宗即位方十岁，章献明肃太后临朝。章献素多智谋，分命儒臣冯章靖元、孙宣公奭、宋宣献绶等采摭历代君臣事迹，为《观文览古》一书，祖宗故事为《三朝宝训》十卷，每卷十事。又纂郊祀仪仗为《卤簿图》三十卷，诏翰林待诏高克明等绘画之，极为精妙，叙事于左，令傅姆辈日夕侍上展玩之，解释诱进，镂板于禁中。《挥麈后录》卷一。
11. 〔刘〕烨登进士第，为龙图阁直学士、权开封府。明肃太后朝独召对，后曰：‘知卿名族十数世，欲一见卿家谱，恐与吾同宗也。’烨曰：‘不敢。’后数问之，度不可免，因陛对，为风眩仆而出。乞出知河南府。《邵氏闻见录》卷十六。
12. 某公在章献明肃后垂箔日，密进《唐武氏七庙图》，后怒，抵之地曰：‘我不作负祖宗事。’仁皇帝解之曰：‘某欲但为忠耳。’后既上宾，仁皇帝每曰：‘某心行不佳。’后竟除平章事。《邵氏闻见后录》卷二十二。
13. 明肃太后欲谒太庙，诏礼官草仪。时学臣皆以《周官》后服进议，佞者密请曰：‘陛下垂帘听大政，号两宫，尊称、山呼及舆御，皆王者制度，入太室岂当以后服见祖宗邪？’遂下诏服衮冕。谏疏交上，复宰臣执议，具不之听。不得已将诞告，赖薛简肃公以关右人语气明直，不文其谈，帘外口奏曰：‘陛下大谒之日，还作汉儿拜邪，女儿拜邪？’明肃无答，是夕报罢。《续湘山野录》。
14. 见吕夷简15。
15. 章献既没，或疑章懿之丧。仁皇遣李用和发其葬视之，容貌如生。使者驰入奏，仁皇于章献神御前，焚香泣告曰：‘自今大娘娘平生分明矣。’仁宗谓刘氏大娘娘，谓杨氏小娘娘。《龙川别志》卷上。《宋名臣言行录》前集卷六。
16. 章献属疾，语于仁宗曰：’愿与祖宗同日为忌。’三月二十九日上仙，乃太宗大忌。后仁宗亦同。前为翁妇，后为母子，此亦国朝之异事。《贵耳集》卷中。



## 杨淑妃

### 《宋人轶事汇编·卷一》

1. 上 `r n("仁宗")` 幼冲 `r n("年龄幼小")` 即位，章献性严，动 `r n("动不动，常常")` 以礼法禁约之，未尝假以颜色 `r n("在态度和言辞上表示友好")` ，章惠以恩抚之。上多苦风痰，章献禁虾蟹海物不得进御，章惠常藏弆 `r n("jǔ。收藏")` 以食之，曰：‘太后何苦虐吾儿如此。’上由是怨章献而亲章惠 `r co("刘氏用心良苦，杨氏不知，抑或明知故不知")` ，谓章献为大娘，章惠为小娘 `r co("为何不是大娘娘、小娘娘")` 。及章献崩，尊章惠为太后，所以奉事曲尽 `r n("曲尽，竭尽")` 恩意。景祐中，薨，神主祔于奉慈庙。《涑水记闻》卷八。



## 李宸妃

### 《宋人轶事汇编·卷一》

1. 章懿李后初在侧微 `r n("卑贱、微贱")` ，事章献明肃。章圣偶过阁中，欲盥手，后捧洗而前，上悦其肤色玉耀 `r n("谓像玉色一样光艳夺目。多喻外表的美")` ，与之言。[后奏]{#李宸妃上位}：‘昨夕忽梦一羽衣之士跣足 `r n("xiǎn zú。赤脚")` 从空而下云：“来为汝子。”’ `r co("好手段")` 时上未有嗣，闻之，大喜云：‘当为汝成之。’是夕召幸，有娠。明年诞育昭陵。昭陵幼年，每穿履袜，即亟令脱去，常徒步禁掖 `r n("谓宫中旁舍。亦泛指宫廷")` ，宫中皆呼为赤脚仙人。赤脚仙人，盖古之得道李君也。《挥麈后录》卷一。《群书类编故事》卷四。

2. 李太后始入掖庭，才十余岁，惟有一弟七岁，太后临别，手结刻丝鞶囊 `r n("pán náng。革制的囊。古人用以盛手巾细物")` 与之，拍其背泣曰：‘汝虽沦落颠沛，不可弃此囊，异时我若遭遇，必访汝，以此为物色也。’言讫，不胜呜咽而去。后其弟佣于凿纸钱家，然常以囊悬于胸臆间，未尝斯须 `r n("斯须。一会儿的功夫,片刻")` 去身也。一日苦下痢，势将不救，为纸家弃于道左。有入内院子者，见而怜之，收养于家。恠 `r n("guài。同“怪”")` 其衣服百结 `r n("多次缝补。比喻衣服破旧")` ，而胸悬鞶囊，因问之，具以告院子 `r n("院子，指仆役")` 。院子惄 `r n("nì。忧郁，伤痛")` 然惊异，盖尝受旨于太后，令物色访其弟也。复问其姓氏、小字、世系甚悉，遂解其囊。明日，持入示太后，及具道本末。是时太后封宸妃，时真宗已生仁宗皇帝矣，闻之悲喜，遽以其事白真宗 `r co("可见宸妃受封后尚留一段时日")` ，遂官之，为右班殿直，即所谓 *李用和* 也。及仁宗立，太后上仙，谥曰章懿，召用和擢 `r n("zhuó。选拔")` 以显官，后至殿前都指挥使，领节钺，赠陇西郡王，世所谓 *李国舅* 者是也。《东轩笔录》卷二。《宋稗类钞》卷三。

[^奉先寺]: 奉先，祭祀祖先。唐佛寺。俗称九间房。位于今河南洛阳伊水东岸龙门山南部半山，依山凿窟，为龙门石窟群中最大的露天大龛。窟内广深各35米多，崖壁上雕出成组的十一尊大佛。布局宏伟，构思完整。其中卢舍那佛像，高17.14米，左右金刚立像，高13米。咸亨三年(672)，武后助脂粉钱两万贯开凿，上元二年(675)底竣工。调露元年(679)大像南置寺，名为奉先寺。

3. 章懿李太后生昭陵 `r n("陵墓名。宋仁宗葬永昭陵，宋人以昭陵作为仁宗的代称")` ，而终章献之世，不知章懿为母也。章懿卒，先殡奉先寺。昭陵以章献之崩，号泣过度。[章惠太后劝帝曰]{#杨淑妃语仁宗}：‘此非帝母，帝自有母宸妃李氏，已卒，在奉先寺[^奉先寺]殡之。’仁宗即以犊车 `r n("牛车")` 亟走奉先寺。撤殡观之，在一大井，上四铁索维之。既启棺，而形容如生，略不坏也。时已遣兵围章献之第矣，既启棺，知非鸩死，乃罢遣之。《默记》卷上。

[^承旨]: 官名。唐代翰林院有翰林学士承旨，位在诸学士上。凡大诰令﹑大废置﹑重要政事，皆得专对。宋元仍其制。元赵孟俯曾为此官，世称赵承旨。明废。参阅唐元稹《翰林承旨学士记》。又五代枢密院有枢密院承旨﹑副承旨;宋代枢密院有都承旨﹑副承旨。初用武臣，后参用文臣。参阅《文献通考．职官十二》。

4. 晏元献公撰《章懿太后神道碑》，破题云：‘五岳峥嵘，昆山出玉；四溟 `r n("海")` 浩渺，丽水生金。’盖言诞育圣躬，实系懿 `r n("美好")` 后。奈仁宗夙 `r n("早")` 以母仪事明肃刘太后，膺 `r n("担当，接受重任 [bear]")` 先帝拥祐之托，难为直致 `r n("直而没有曲折")` ，然才者则爱其善比 `r n("比方")` 也。独仁宗不悦，谓晏曰：‘何不直言诞育朕躬，使天下知之？’晏公具以前意奏之。上曰：‘此等事卿宜置之，区区不足较，当更别改。’晏曰：‘已焚草 `r n("烧掉奏稿，以示谨密")` 于神寝。’上终不悦。迨升祔 `r n("shēng fù。升入祖庙附祭于先祖")` ，二后赦文 `r n("赦文。朝廷公布赦罪的文书")` *孙承旨* `r n("亦作“承指”。逢迎意旨。或官名")` [^承旨] 抃 `r n("biàn。拍手、鼓掌")` 当笔 `r n("主持撰拟文稿")` ，协圣意直叙曰：‘章懿太后丕拥庆羡 `r n("庆羡。以为有幸而欣羡")` ，实生眇冲 `r n("miǎo chōng。幼小的人。帝王自称之词")` ，顾复 `r n("指父母之养育，出自.《诗．小雅．蓼莪》")` 之恩深，保绥 `r n("bǎo suí。使得到保全，获得安定")` 之念重。神驭既往，仙游斯邈 `r n("遥远")` 。嗟乎！为天下之母，育天下之君，不逮 `r n("到，及")` 九重之承颜 `r n("顺承尊长的颜色。谓侍奉尊长")` ，不及乎四海之致养，念言一至，追慕增结。’上览之，感泣弥月。明赐之外，悉以东宫旧玩密赉 `r n("lài。赏赐")` 之。岁余，参大政 `r n("国家政务")` 。《湘山野录》卷上。《西塘集耆旧续闻》卷五。

5. 孙文懿公 `r co("同上文“孙承旨”")` 为翰林学士，撰《进祔 `r n("fù。奉新死者的神主入庙，与先祖合祭")` 李太后赦文》曰：‘章懿太后丕拥庆羡，实生眇冲，顾复之恩深，保绥之念重。神驭既往，仙游斯邈。嗟乎！为天下之母，育天下之君，不逮乎九重之承颜，不及乎四海之致养，念言一至，追慕增结。’仁宗皇帝览之，感泣弥月。公自此遂参大政。帝问文懿曰：‘卿何故能道朕心中事？’公曰：‘臣少以庶子不齿 `r n("不愿意提到,表示极端鄙视")` 于兄弟，不及养母，以此知陛下圣心中事。’上为之流涕。先是晏元献公撰《章懿太后神道碑》曰：‘五岳峥嵘，昆山出玉；四溟浩渺，丽水生金。’盖以明肃太后为尊也。学士大夫嘉其善比，独仁宗不悦。`r co("仁宗多愁善感，心思细腻")` 《邵氏闻见录》卷二。


## 郭后

宋仁宗宫内。

### 《宋人轶事汇编·卷二》

1. 康定二年，富文忠为知制诰。先是昭陵聘后，蜀中有王氏女，姿色冠世，入京备选。章献一见，以为妖艳太甚，恐不利于少主，乃以嫁其侄从德，而择郭后位中宫。上终不乐之。王氏之父蒙正，由刘氏婣党屡典名藩。未几，从德卒。至是，中批王氏封遂国夫人，许入禁中。文忠适当草制，封还，抗章甚力，遂并寝其旨。外制缴词头，盖自此始。《挥麈后录》卷二。
2. 先朝命郭后观奉宸库，后辞曰：‘奉宸国之宝库，非妇人所当入。陛下欲惠赐六宫，愿量颁之，妾不敢奉诏。’上为之止。《涑水记闻》卷六。
3. 庄献初崩，上与吕夷简谋，以夏竦等皆庄献太后之党，悉罢之。退告郭后，郭后曰：‘夷简独不附太后邪？但多机巧，善应变耳。’由是并夷简罢之。是日，夷简押班，闻唱其名，大骇，不知其故。夷简素与内侍副都知阎文应等相结，使为中诇，久之，乃知事由郭后。夷简由是恶郭后。《涑水记闻》卷五。《宋名臣言行录》前集卷九。
4. 〔郭〕后之获罪也，上直以一时之忿，且为吕夷简、阎文应所谮，故废之。既而悔之。后出居瑶华宫，章惠太后亦逐杨、尚二美人，而立曹后。久之，上游后园，见郭后故肩舆，凄然伤之，作《庆金枝》词，遣小黄门赐之，且曰：‘当复召汝。’夷简、文应闻之，大惧。会后有小疾，文应使医官故以药发其疾。疾甚，未绝，文应以不救闻，遽以棺敛之。王伯庸时为谏官，上言：‘郭后未卒，数日先具棺器，请推按其起居状。’上不从，但以后礼葬于佛舍而已。《涑水记闻》卷五。《宋名臣言行录》前集卷九。

## 曹后

### 《宋人轶事汇编·卷二》

1. 天圣中，童谣云：‘曹门好，有好好；曹门高，有高高。’其后，今太皇太后为皇后，太皇太后姓曹氏。英宗皇帝即位，而高太后为皇后。高后，曹氏之所出。《东斋记事》卷一。
2. 天圣、明道间，京师盛歌一曲曰《曹门高》。未几，慈圣太后受册中宫，人以为验矣。其后宣仁与慈圣皆垂箔摄政，而宣仁实慈圣之甥，以故选配英庙，则征兆之意若曰：‘曹门之高，当相继而起也。’《老学庵笔记》卷七。
3. 慈圣太后在女家时，尝因寒食与家人戏掷钱。一钱盘旋久之，遂侧立不仆，未几被选。《石林燕语》卷七。《避暑漫钞》。
4. 京兆李植，字化光，观察使士衡之孙。自少年好道，不乐婚宦。初，为侍禁，约婚慈圣。既娶，迎入门，见鬼神千万在其前。植惊走，逾墙避之。后时即还父母家，俄选为后焉。《默记》卷中。《甲申杂记》。《玉芝堂谈荟》卷一。
5. 庆历中，亲事官乘醉入禁中，仁宗皇帝遣谕：‘皇后贵妃闭阁勿出。’后谨听命，贵妃直趋上前。明日，上对辅臣泣下，辅臣亦泣，首相陈恭公毅然无改容。上谓：‘贵妃冒不测而来，斯可宠也。’枢相乘间启废立之议。张文定得其说，即诣恭公，以为不可。恭公持议甚坚。久而上复问之，梁相适进曰：‘一之已甚，其可再乎？’声甚厉。既退，上留适曰：‘朕止欲稍加妃礼，本无他意，卿可安心。’群论遂止。《闻见近录》。《道山清话》。
6. 温成有宠，慈圣光献尝以事忤旨。仁宗一日语宰相梁适曰：‘废后之事如何？’适进曰：‘闾巷小人尚不忍为，陛下万乘之主，岂可再乎？’谓前已废郭后也。帝意解，因间语光献曰：‘我尝欲废汝，赖梁适谏我，汝乃得免。汝之不废，适之力也。’后适死，光献常感之。忽一日，出五百万作醮，帝适见其事，问之，光献以实告。帝叹息。自后岁率为之，至光献上仙乃止。《曲洧旧闻》卷二。

7. 慈圣识虑，过人远甚。仁宗一夕饮酒温成阁中，极懽，而酒告竭。夜漏向晨矣，求酒不已。慈圣云：‘此间亦无有。’左右曰：‘酒尚有，而云无，何也？’答曰：‘上饮懽，必过度。万一以过度而致疾，归咎于我，我何以自明？’翼日，果服药。言者乃叹服。《曲洧旧闻》卷一。
8. 子瞻尝言韩庄敏对客称：仁宗时，一夜，三更以来，有中使于慈圣殿传宣。慈圣起，着揹子不开门，但于门缝中问云：‘传宣有甚事？’中使云：‘皇帝起饮酒尽，问皇后殿有酒否？’慈圣云：‘此中便有酒，亦不敢将去。夜已深，奏知官家，且歇息去。’更不肯开门纳中使。《道山清话》。
9. 慈圣曹后，嘉祐中幸相国寺烧香。后有百宝念珠价直千万，挂领间，登殿之次忽不见。仁宗大怒，命尽系从卫之人，大索都下。捕吏惶惧，物色不可得。因念寺前常有小儿数人嬉戏自若，而不知其所从来，漫往问之。中一丫髻女子，年十二三，忽笑谓吏曰：‘前日偶取之，忘记还去，今见挂寺塔之颠火珠上，当自往取之。’吏知其异人也，再拜以请，女子还，遂入塔中。吏辈仰视，见第十三级窗中出一手，与相轮等，观者万人，恐怖毛竖，须臾不见。而女子手提数珠而下，授吏。复请曰：‘中旨严急，愿具往以取信。’儿亦不辞。行数十步，立化通衢。开封尹上其事，上嗟异久之，凡坐累者皆获赦云。《投辖录》。
10. 见宋仁宗72。
11. 台官论濮王事甚急。……是〔正〕月二十间，天章阁赏小桃，因以劝太后。太后有酒，所卧阁中，内臣高居简、苏利涉从上至太后榻前拜，以书一封进太后，求一押字。太后酒未解，不知书所言何事，遂从之。既而书出，乃太后命中书尊濮王为皇等事。明日遂奉行，太后始知。京师諠然，下至闾巷，亦以为不可。太后力争不已。二十二日乃下诏罢濮王称皇等事。《宋名臣言行录》后集卷五引《南丰杂识》。
12. 见韩琦66。
13. 见韩琦67。
14. 见韩琦68。
15. 曹后称制日，韩琦欲还政天子，而御宝在太后阁，皇帝行幸即随驾，琦因请具素仗祈雨。比乘舆还，御宝更不入太后阁，即于帘前具述皇帝圣德，都人瞻仰，无不欢慰，且言天下事久烦圣虑。太后怒曰：‘教做也由相公，不教做也由相公。’琦独立帘外不去。及得一言，有允意，即再拜。驾起，遂促仪鸾司拆帘。上自此亲政。《孙公谈圃》卷中。

16. 韩魏公薨，其子孙仿郭汾阳着《家传》十卷，具载魏公功业。至英宗即位之初，乃云光献信谗，屡有不平之语，魏公以危言感动曰：‘若官家失照管，太后亦未得安稳。’又言：太后曾问汉昌邑王事如何。又云：太后言：‘昨夕梦甚异，见这孩儿却在庆宁宫。谓英宗复在旧邸。’魏公曰：‘却在庆宁宫，乃是圣躬复旧之兆，此是好梦。’又言：英宗不豫，魏公奏曰：‘大王长立，且与照管。谓神宗。’后怒曰：‘尚欲旧窠中求兔耶？’又言：太后对大臣泣诉英宗语曰：‘富弼意主太后。’又云：太后欲御前殿，魏公论奏云云，乃止。又云：台谏有章，乞早还政，太后泣曰：‘若放下，更岂见眼道耶！’如此等事尚多，皆诞妄不恭，非所宜言。韩氏子孙，贩卖松槚，张大勋业，以希进用，殊不知陷其父祖于不义也。王岩叟者，父子为魏公之客，亦着《魏公遗事》一编，其记魏公言行甚详。至论光献权同听政事，亦为欺诞。谓太后还政之后，魏公劝英宗加仪卫，帝曰：‘相公休奖纵母后。’又谓魏公对太后曰：‘自家无子，不得不认。’察其意，以谓英宗非魏公不得立，既立，非魏公不得安也。《邵氏闻见录》卷三。
17. 神庙当宁，慨然兴大有为之志，思欲问西北二境罪。一日被金甲诣慈寿宫，见太皇太后曰：‘娘娘，臣着此好否？’曹后迎笑曰：‘汝被甲甚好。虽然，使汝至衣此等物，则国家何堪矣。’神庙默然心服，遂卸金甲。《铁围山丛谈》卷一。
18. 神宗初，欲破夏国。……一日，帝衣黄金甲以见光献太后，后曰：‘官家着此，天下人如何？脱去，不祥。’又欲京城安楼橹，后亦不许，但以库贮于诸门。《邵氏闻见录》卷三。
19. 见宋神宗9。
20. 禁中近清明节，神宗侍曹太皇，因语：‘自来却无人做珠子鞍辔。虽云太华，然亦好也。’太皇闻此语，已密令人描样矣。不数日，实促就珠子鞍辔，传宣索玉鞍辔一副。神宗莫测所欲用，亦莫敢问，依旨进入。太后令送后苑拆修，遂施珠鞯焉，其上作小红罗销金坐子，劣可容体，甫近上巳，以鞍架载之送神宗。神宗大感悦，取小乌马于福宁殿亲试之。……光献太皇太后疾病稍间，神宗亲制一小辇，极为轻巧，以珠玉黄金饰之，进于太皇云：‘娘娘试乘此辇，往凉殿散心。’太皇曰：‘今日意思无事，天气亦好。’遂载而之凉殿。太后扶其左，神宗扶其右，太皇下辇曰：‘官家、太后亲自扶辇，当时在曹家作女时，安知有今日之盛！’喜见颜色。王正仲进光献挽词云：‘珠鞯锡御恩犹在，玉辇亲扶事已空。’盖用此两事也。《孔氏谈苑》卷一。《宋诗纪事》卷十七。
21. 东坡既就逮下御史府，一日，慈圣曹太皇语上曰：‘官家何事数日不怿？’对曰：‘更张数事未就绪，有苏轼者，辄加谤讪，至形于文字。’太皇曰：‘得非轼、辙乎？’上惊曰：‘娘娘何以闻之？’曰：‘吾尝记仁宗皇帝策试制举人罢归，喜而言曰：“朕今日得二文士，谓苏轼、辙也。然吾老矣，虑不能用，将以遗后人，不亦可乎？”’因泣问二人安在，上对以轼方系狱，则又泣下，上亦感动，始有贷轼意。《泊宅编》三卷本卷上、又十卷本卷一。《贵耳集》卷上。

22. 慈圣光献大渐，上纯孝，欲肆赦。后曰：‘不须赦天下凶恶，但放了苏轼足矣。’时子瞻对吏也。后又言：‘昔仁宗策贤良归，喜甚，曰：“吾今日又为子孙得太平宰相两人。”盖轼、辙也，而杀之，可乎！’上悟，即有黄州之贬。《西塘集耆旧续闻》卷二。
23. 光献太皇太后，元丰四年春感疾，以文字一函封鐍甚严，付神宗曰：‘俟吾死开之，唯不可因此罪人。’帝泣受。后疾愈，帝复纳此函。后曰：‘姑收之。’是年七月，后上仙。帝开函，皆仁宗欲立英宗为皇嗣时，臣僚异议之书也。神宗执书恸哭，以太皇太后遗训，不敢追咎其人。故帝宫中服三年之丧。《邵氏闻见录》卷三。
24. 〔慈圣〕晚岁疾，病急，顾左右，问此为何日。左右对以十月二十日，实太祖大忌日也。后颔之，迺自语曰：‘只此日去，只此日去，免烦他百官。’盖谓不欲别日立忌，使百官有司有奉慰行香之劳，就是日则免。于是二十日崩。《铁围山丛谈》卷一。《避暑漫钞》。
25. 慈圣曹太后工飞白，盖习观昭陵落笔也。先人旧藏一‘美’字，径二尺许，笔势飞动，用慈寿宫宝。今不知何在矣。《老学庵笔记》卷二。

## 张贵妃

### 《宋人轶事汇编·卷二》

1. 西京留台李建中，博雅多艺，其子宗鲁善相人。一年春榜之京师，命择婿。行次任村逆旅，方就食，有丈夫荷布囊，从驱驴，亦就食于逆旅。宗鲁一见，前揖寒温，延之共案，询其所自，曰：‘今春不第，将还洛也。’宗鲁不复之京师，与之同归洛中。其父诘之，曰：‘今既得贵婿，可复回矣。此人生不出选调，死封真王。’于是婿之，乃张尧封也。实生温成皇后，天圣中登进士第，终亳州军事推官，后封清河郡王。《画墁录》。《归田录》卷二。《新编分门古今类事》卷十。《宋稗类钞》卷七。
2. 吴越王子太师雅之女适张氏，生子名尧封，与尧佐为宗表兄弟。尧封游学南京，遂娶曹氏女。尧封俊迈，从学山东孙明复，至其舍，执事皆尧封妻女，如事亲焉。时文异倅南京，子彦博、彦若竝师明复，明复遂荐尧封于文氏为门客，张、文之好，始于此矣。尧封就举，与张文定同保，将引试，语文定曰：‘宗表兄自无锡宰归，当往求举资。’及还，尧佐但与钱五百文。后尧封举进士第，任石州推官卒。其女入宫中为婕妤沈氏养女，是为温成皇后。久之，得幸仁宗，贵宠日盛。时相乃为访其族氏，会尧佐以太常博士知开州还，时相因以白上。……潞公召自蜀，将至阙下，贵妃亲视供帐以待，其夫人入谢。众论諠然。时贝州王则叛，仁宗北顾。妃乃阴喻潞公贝州事，明镐将有成绩，可请行。潞公既行，贝州平，潞公以功拜相，群论渐息。曹氏后封越国夫人。《闻见近录》。
3. 庆历中，广州有死蕃商没官珍珠，有司贱估其直，十分价中才及一分，令郡官分买之，为本路监司按劾，计赃并珍珠赴京师具案。既上，仁宗时于禁中闻之，且命取所估珍珠，上与宫官同阅，爱其珍异。张贵妃在侧，意欲得之，上依所估价，出禁中钱易之以赐贵妃。时禁中同列因是有于上乞旨和买，缘此京师珠价腾踊，上颇知之。一日，上于别殿赏牡丹，妃嫔毕集，贵妃最后至，乃以前日珍珠为首饰，以夸同辈，欲至上前。上望见，以袖掩面曰：‘满头白纷纷的，都没些忌讳。’贵妃慙赧，起易之。乃大悦，使人各簪牡丹一枝，自是禁中更不戴珍珠，价大减。《元城语录》卷中。《苕溪渔隐丛话》后集卷十九。
4. 仁宗一日幸张贵妃阁，见定州红甆器，帝坚问曰：‘安得此物？’妃以王拱辰所献为对，帝怒曰：‘尝戒汝勿通臣僚馈遗，不听何也？’因以所持柱斧碎之。妃愧谢，久之乃已。妃又尝侍上元宴于端门，服所谓灯笼锦者，上亦怪问。妃曰：‘文彦博以陛下眷妾，故有此献。’上终不乐。后潞公入为宰相，台官唐介言其过，及灯笼锦事，介虽以对上失礼远谪，潞公寻亦出判许州，盖上两罢之也。或云灯笼锦者，潞公夫人遗张贵妃，公不知也。唐公之章与梅圣俞书窜之诗，过矣。《邵氏闻见录》卷二。《宋名臣言行录》后集卷五。
5. 见文彦博16。
6. 见宋祁20。
7. 张尧佐除宣徽使，以廷论未谐，遂止。久之，上以温成故，欲申前命。一日，将御朝，温成送至殿门，抚背曰：‘官家今日不要忘了宣徽使。’上曰：‘得，得！’既降旨，包拯乞对，大陈其不可，反覆数百言，音吐愤激，唾溅帝面，帝卒为罢之。温成遣小黄门次第探伺，知拯犯颜切直，迎拜谢过。帝举袖拭面曰：‘中丞向前说话，直唾我面。汝只管要宣徽使、宣徽使，汝岂不知包拯是御史中丞乎？’《曲洧旧闻》卷一。
8. 金橘产于江西，以远难致，都人初不识。明道、景祐初，始与竹子具至京师。竹子味酸，人不甚喜，后遂不至。而金橘香清味美，置之罇俎间，光彩灼烁如金弹丸，诚珍果也。都人初亦不甚贵，其后因温成皇后尤好食之，由是价重京师。《归田录》卷二。《游宦纪闻》卷二。



