on:
  push:
    branches:
      - main
  pull_request:
    branches: main
  # to be able to trigger a manual build
  workflow_dispatch:


name: renderbook

jobs:
  preproc:
    name: Preprocess Reference Books
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/proc_book/requirements.txt
      - name: Process books
        run: |
          python tools/proc_book/proc.py --tag_prefix 唐轶 --output_dir _out tag --alt books/98-anecdotes-tang-out.Rmd
          python tools/proc_book/proc.py --tag_prefix 宋轶 --output_dir _out tag --alt books/98-anecdotes-song-out.Rmd
          python tools/proc_book/proc_docx.py --output_dir _out tools/data/90-3kingdoms.docx
          python tools/proc_book/proc_mobi.py --output_dir _out tools/data/60-24-history-literature
      - name: Archive processed books
        uses: actions/upload-artifact@v3
        with:
          name: preproc_output
          path: _out

  bookdown:
    name: Render Book
    runs-on: macos-latest
    needs: preproc
    steps:
      - uses: actions/checkout@v3
      - name: Download preprocessing results
        uses: actions/download-artifact@v3
        with:
          name: preproc_output
          path: ./
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown", "bookdown", "bookdownplus", "downlit", "xml2", "DiagrammeR"))'
      - name: Render Book
        # timeout-minutes: 1
        run: Rscript -e 'rmarkdown::render_site(output_format = "bookdown::bs4_book", encoding = "UTF-8")'
      - uses: actions/upload-artifact@v3
        with:
          name: _book
          path: _book/

# Need to first create an empty gh-pages branch
# see https://pkgdown.r-lib.org/reference/deploy_site_github.html
# and also add secrets for a GH_PAT and EMAIL to the repository
# gh-action from Cecilapp/GitHub-Pages-deploy
  checkout-and-deploy:
    name: Deploy Book
    runs-on: ubuntu-latest
    needs: bookdown
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          # Artifact name
          name: _book # optional
          # Destination path
          path: _book # optional
      - name: Deploy 🚀
        # only deploy when push to main
        if: github.event_name != 'pull_request'
        # Beware of the action permisstion as stated here:
        # https://github.com/JamesIves/github-pages-deploy-action#permission-settings-%EF%B8%8F
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # The branch the action should deploy to.
          branch: gh-pages
          # The folder the action should deploy. Adapt if you changed in Quarto config
          folder: _book
